server:
  port: 8080
spring:
  security:
    user:
      name: root
      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordering
    username: root
    password: 1234
#    url: jdbc:mariadb://my-db.crs4606qgf7x.us-east-1.rds.amazonaws.com:3306
#    username: admin
#    password: r3fPWeqJfSPmtYODGXDW
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    show-sql: true

jwt:
  expiration: 300 #300분
  secretKey: sejong




