# 워크플로우의 이름을 지정
name: Deploy to Ec2 with Jar

# push 이벤트 지정
# main 브랜치에 push될 때마다 workflow가 실행되도록 지정
on:
  push:
    branches:
      - main

jobs:
  # 작업의 이름 지정
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        working-directory: ./240131_Ordering_Spring
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Copy jar to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST1 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./240131_Ordering_Spring/build/libs/*.jar"
          target: "/home/${{ secrets.EC2_USERNAME }}"