name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: npm install
        working-directory: ./ordering_front
        run: npm install

      - name: npm build
        working-directory: ./ordering_front
        run: npm run build

      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY}}
          aws-secret-access-key-id: ${{secrets.AWS_S3_SECRET_KEY}}
          aws-regin: "us-east-1"

      - name: deploy to s3
        run: |
          aws s3 cp ./ordering_front/dist s3://order-system-vue2/ --recursive

