#name: Deploy to AWS S3
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: setup node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '20'
#
#      - name: npm install
#        run: npm install
#
#      - name: npm build
#        run: npm build
#
#      - name: setup aws cli
#
#      - name: deploy to s3
#
#