name: Deploy to Ec2 With docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 우분투에 도커가 들어있다.
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        working-directory: ./ordering_server
        run: docker build -t lifedesigner88/ordering-backend:v2 .

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: docker push lifedesigner88/ordering-backend:v2